---
title: "assignments 2.1 and 2.2"
author: "Daniel Kerstan"
date: "10/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dataRetrieval)
library(tidyverse)
library(lubridate)
library(metajam)
library(here)
```


#Assignment 2.1


```{r}

site_numbers <- c("11118500", "11113500")
parameter_cd <- "00060"
start_date <- "2021-10-01"
end_date <- "2021-10-05"

discharge_data <- readNWISdv(site_numbers, parameter_cd, start_date, end_date)
discharge_data <- renameNWISColumns(discharge_data)

discharge_data <- discharge_data %>% 
  mutate(location = case_when(site_no == "11118500" ~ "ventura",
                              site_no == "11113500" ~ "santa paula"))


# Best way to query multiple sites is to store a character vector of site numbers as the site_numbers object
```

```{r}

```


```{r}
ggplot(discharge_data, aes(x = Date, y = Flow)) +
  geom_line(aes(color = location)) +
  labs(y = "Discharge") +
  theme_minimal()
```

```{r}
# get stream flow data for only oct 4-5

site_numbers <- c("11118500", "11113500")
parameter_cd <- "00060"
start_datetime <- "2021-10-04"
end_datetime <- "2021-10-05"

discharge_data_2 <- readNWISdata(sites = site_numbers, service = "iv", parameterCd = parameter_cd, startDate = start_datetime, endDate = end_datetime)
discharge_data_2 <- renameNWISColumns(discharge_data_2)

discharge_data_2 <- discharge_data_2 %>% 
  mutate(location = case_when(site_no == "11118500" ~ "ventura",
                              site_no == "11113500" ~ "santa paula"))

discharge_max_ventura <- discharge_data_2 %>% 
  filter(location == "ventura") %>% 
  filter(Flow_Inst == max(Flow_Inst)) %>% 
  filter(day(dateTime) == 05)

discharge_max_santa_paula <- discharge_data_2 %>% 
  filter(location == "santa paula") %>% 
  filter(Flow_Inst == max(Flow_Inst))

ggplot() +
  geom_rect(data = discharge_max_ventura, aes(xmin = min(dateTime), xmax = max(dateTime), ymin = 0, ymax = 1.2, fill = "ventura max"),
            alpha = 0.2,
            show.legend = TRUE) +
  geom_rect(data = discharge_max_santa_paula, aes(xmin = min(dateTime), xmax = max(dateTime), ymin = 0, ymax = 1.2, fill = "santa paula max"), 
            alpha = 0.2,
            show.legend = TRUE) +
  scale_color_manual(aesthetics = "fill", breaks = c("ventura max", "santa paula max"), values = c("cadetblue1", "lightpink")) +
  geom_line(data = discharge_data_2, aes(x = dateTime, y = Flow_Inst, color = location)) +
  labs(y = "Discharge") +
  theme_minimal() +
  scale_y_continuous(limits = c(0, 1.2), expand = c(0,0)) +
  labs(x = "Time")
  

```



#Assignment 2.2

```{r, eval=FALSE}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A7fc6f6db-c5ea-426a-a743-1f2edafb43b8"

path <- here("data")


data_path <- metajam::download_d1_data(data_url, path)


```

```{r}
data <- metajam::read_d1_files(here("data", "doi_10.5063_F1CJ8BPH__household_language__csv"))

```

```{r}
house <- data$data

house_sub <- house %>% 
  group_by(Year) %>% 
  select(total, speak_only_english) %>% 
  summarize(sum_total = sum(total), sum_speak_only_english = sum(speak_only_english) ) %>% 
  ungroup() %>% 
  filter(Year >= 2009) %>% 
  group_by(Year) %>% 
  mutate(percent = sum_speak_only_english / sum_total)



ggplot(house_sub, aes(x = Year, y = percent)) +
  geom_line() +
  scale_x_continuous(breaks = c(2009, 2010, 2011, 2012, 2013, 2014, 2015)) +
  labs(title = "Percentage of Alaskan households speaking English", y = NULL)


```
